### ISSUE TITLE
Crash in a modpack

### ISSUE THREAD

**Issue by ghost** [JamiesWhiteShirt/clothesline#10]
i playd my private modpack and the game crashed out of nothing the mod vanillafix said it was this mod

Crashreport:
---- Minecraft Crash Report ----
// Oops.

Time: 2018-10-13 10:02:39 CEST
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NullPointerException: Tried to send data to client before the player exists.
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1087)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3940)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NullPointerException: Tried to send data to client before the player exists.
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
    at forestry.core.network.PacketHandler.lambda$checkThreadAndEnqueue$0(PacketHandler.java:76)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_181, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1348056144 bytes (1285 MB) / 3314024448 bytes (3160 MB) up to 3817865216 bytes (3641 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
  IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.4.2766 Optifine OptiFine_1.12.2_HD_U_E2 167 mods loaded, 167 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State           | ID                       | Version                      | Source                                        | Signature                                |
       |:--------------- |:------------------------ |:---------------------------- |:--------------------------------------------- |:---------------------------------------- |
       | UCHIJAAAAAAAAAA | minecraft                | 1.12.2                       | minecraft.jar                                 | None                                     |
       | UCHIJAAAAAAAAAA | mcp                      | 9.42                         | minecraft.jar                                 | None                                     |
       | UCHIJAAAAAAAAAA | FML                      | 8.0.99.99                    | forge-1.12.2-14.23.4.2766-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAAAAAAAAAA | forge                    | 14.23.4.2766                 | forge-1.12.2-14.23.4.2766-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAAAAAAAAAA | OpenEye                  | 0.8                          | OpenEye-1.12.2-0.8.jar                        | None                                     |
       | UCHIJAAAAAAAAAA | openmodscore             | 0.12                         | minecraft.jar                                 | None                                     |
       | UCHIJAAAAAAAAAA | foamfixcore              | 7.7.4                        | minecraft.jar                                 | None                                     |
       | UCHIJAAAAAAAAAA | clothesline-hooks        | 1.12.2-0.0.1.0               | minecraft.jar                                 | None                                     |
       | UCHIJAAAAAAAAAA | botania_tweaks_core      | -100                         | minecraft.jar                                 | None                                     |
       | UCHIJAAAAAAAAAA | akashictome              | 1.2-10                       | AkashicTome-1.2-10.jar                        | None                                     |
       | UCHIJAAAAAAAAAA | alfinivia                | 0.4hotfix                    | Alfinivia-0.4hotfix.jar                       | None                                     |
       | UCHIJAAAAAAAAAA | crafttweaker             | 4.1.9                        | CraftTweaker2-1.12-4.1.9.jar                  | None                                     |
       | UCHIJAAAAAAAAAA | mtlib                    | 3.0.5                        | MTLib-3.0.5.jar                               | None                                     |
       | UCHIJAAAAAAAAAA | modtweaker               | 4.0.13                       | modtweaker-4.0.13.jar                         | None                                     |
       | UCHIJAAAAAAAAAA | forgelin                 | 1.7.4                        | Forgelin-1.7.4.jar                            | None                                     |
       | UCHIJAAAAAAAAAA | baubles                  | 1.5.2                        | Baubles-1.12-1.5.2.jar                        | None                                     |
       | UCHIJAAAAAAAAAA | thaumcraft               | 6.1.BETA25                   | Thaumcraft-1.12.2-6.1.BETA25.jar              | None                                     |
       | UCHIJAAAAAAAAAA | thaumcraftresearchloader | 1.0                          | thaumcraftresearchloader-1.0.jar              | None                                     |
       | UCHIJAAAAAAAAAA | thaumic_arcana           | 0.6.0                        | Thaumic+Arcana-0.6.0.jar                      | None                                     |
       | UCHIJAAAAAAAAAA | jei                      | 4.12.0.216                   | jei_1.12.2-4.12.0.216.jar                     | None                                     |
       | UCHIJAAAAAAAAAA | theoneprobe              | 1.4.23                       | theoneprobe-1.12-1.4.23.jar                   | None                                     |
       | UCHIJAAAAAAAAAA | ctm                      | MC1.12.2-0.3.2.18            | CTM-MC1.12.2-0.3.2.18.jar                     | None                                     |
       | UCHIJAAAAAAAAAA | twilightforest           | 3.8.689                      | twilightforest-1.12.2-3.8.689-universal.jar   | None                                     |
       | UCHIJAAAAAAAAAA | immersiveengineering     | 0.12-85                      | ImmersiveEngineering-0.12-85.jar              | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | UCHIJAAAAAAAAAA | alternatingflux          | 0.12.2-1                     | alternatingflux-0.12.2-1.jar                  | None                                     |
       | UCHIJAAAAAAAAAA | antiqueatlas             | 4.4.9                        | antiqueatlas-1.12.2-4.4.9.jar                 | None                                     |
       | UCHIJAAAAAAAAAA | antiqueatlasoverlay      | 1.2                          | antiqueatlas-1.12.2-4.4.9.jar                 | None                                     |
       | UCHIJAAAAAAAAAA | examplemod               | 1.0                          | antiqueatlas-1.12.2-4.4.9.jar                 | None                                     |
       | UCHIJAAAAAAAAAA | applecore                | 3.1.1                        | AppleCore-mc1.12.2-3.1.1.jar                  | None                                     |
       | UCHIJAAAAAAAAAA | appleskin                | 1.0.9                        | AppleSkin-mc1.12-1.0.9.jar                    | None                                     |
       | UCHIJAAAAAAAAAA | aqueducts                | 0.3                          | Aqueducts-0.3.jar                             | None                                     |
       | UCHIJAAAAAAAAAA | armorchroma              | 1.4-beta                     | armorchroma-1.4-beta-1.12.2.jar               | None                                     |
       | UCHIJAAAAAAAAAA | aroma1997core            | 1.3.0.2                      | Aroma1997Core-1.12.2-1.3.0.2.jar              | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | UCHIJAAAAAAAAA  | aromabackup              | 2.1.1.3                      | AromaBackup-1.12.2-2.1.1.3.jar                | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | UCHIJAAAAAAAAA  | aromabackuprecovery      | 2.1.1.3                      | AromaBackup-1.12.2-2.1.1.3.jar                | None                                     |
       | UCHIJAAAAAAAAA  | astralsorcery            | 1.9.4                        | astralsorcery-1.12.2-1.9.4.jar                | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
       | UCHIJAAAAAAAAA  | morphtool                | 1.2-16                       | Morph-o-Tool-1.2-16.jar                       | None                                     |
       | UCHIJAAAAAAAAA  | psi                      | r1.1-59                      | Psi-r1.1-59.jar                               | None                                     |
       | UCHIJAAAAAAAAA  | quark                    | r1.5-130                     | Quark-r1.5-130.jar                            | None                                     |
       | UCHIJAAAAAAAAA  | autoreglib               | 1.3-20                       | AutoRegLib-1.3-20.jar                         | None                                     |
       | UCHIJAAAAAAAAA  | auto_third_person        | 1.1.0                        | autothirdperson-1.1.0.jar                     | None                                     |
       | UCHIJAAAAAAAAA  | baubleshulkerboxes       | 1r                           | BaubleShulkerBoxes-1.12.2-1r.jar              | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | UCHIJAAAAAAAAA  | betteradvancements       | 0.0.7.42                     | BetterAdvancements-1.12.2-0.0.7.42.jar        | None                                     |
       | UCHIJAAAAAAAAA  | betterfoliage            | 2.1.10                       | BetterFoliage-MC1.12-2.1.10.jar               | None                                     |
       | UCHIJAAAAAAAAA  | betterstorage            | 3.0.0.2                      | BetterStorageToo-1.12.2-3.0.0.2.jar           | None                                     |
       | UCHIJAAAAAAAAA  | forestry                 | 5.8.1.350                    | forestry_1.12.2-5.8.1.350.jar                 | None                                     |
       | UCHIJAAAAAAAAA  | binniecore               | 2.5.0.168                    | binnie-mods-1.12.2-2.5.0.168.jar              | None                                     |
       | UCHIJAAAAAAAAA  | binniedesign             | 2.5.0.168                    | binnie-mods-1.12.2-2.5.0.168.jar              | None                                     |
       | UCHIJAAAAAAAAA  | genetics                 | 2.5.0.168                    | binnie-mods-1.12.2-2.5.0.168.jar              | None                                     |
       | UCHIJAAAAAAAAA  | botany                   | 2.5.0.168                    | binnie-mods-1.12.2-2.5.0.168.jar              | None                                     |
       | UCHIJAAAAAAAAA  | extrabees                | 2.5.0.168                    | binnie-mods-1.12.2-2.5.0.168.jar              | None                                     |
       | UCHIJAAAAAAAAA  | extratrees               | 2.5.0.168                    | binnie-mods-1.12.2-2.5.0.168.jar              | None                                     |
       | UCHIJAAAAAAAAA  | biomesoplenty            | 7.0.1.2399                   | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar | None                                     |
       | UCHIJAAAAAAAAA  | guideapi                 | 1.12-2.1.6-61                | Guide-API-1.12-2.1.6-61.jar                   | None                                     |
       | UCHIJAAAAAAAAA  | bloodmagic               | 1.12.2-2.3.3-101             | BloodMagic-1.12.2-2.3.3-101.jar               | None                                     |
       | UCHIJAAAAAAAAA  | bloodmoon                | 1.5.3                        | Bloodmoon-MC1.12.2-1.5.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | UCHIJAAAAAAAAA  | bloodylib                | 1.12.2                       | bloodylib-1.0.0.jar                           | None                                     |
       | UCHIJAAAAAAAAA  | bookshelf                | 2.3.563                      | Bookshelf-1.12.2-2.3.563.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAAAAAAAAA  | botania_tweaks           | 1.7                          | botaniatweaks-1.7.jar                         | None                                     |
       | UCHIJAAAAAAAAA  | botania                  | r1.10-356                    | Botania+r1.10-356.jar                         | None                                     |
       | UCHIJAAAAAAAAA  | bullseye                 | 3.0.6                        | Bullseye-1.12.2-3.0.6.jar                     | None                                     |
       | UCHIJAAAAAAAAA  | chisel                   | MC1.12.2-0.2.1.35            | Chisel-MC1.12.2-0.2.1.35.jar                  | None                                     |
       | UCHIJAAAAAAAAA  | cathedral                | 1.12.2-1.9.7f                | Cathedral-1.12.2-1.9.7f.jar                   | None                                     |
       | UCHIJAAAAAAAAA  | clienttweaks             | 3.1.9                        | ClientTweaks_1.12.2-3.1.9.jar                 | None                                     |
       | UCHIJAAAAAAAAA  | dynamictrees             | 1.12.2-0.8.2                 | DynamicTrees-1.12.2-0.8.2.jar                 | None                                     |
       | UCHIJAAAAAAAAA  | dynamictreesbop          | 1.12.2-1.3.2                 | DynamicTreesBOP-1.12.2-1.3.2.jar              | None                                     |
       | UCHIJAAAAAAAAA  | rustic                   | 1.0.12                       | rustic-1.0.12.jar                             | None                                     |
       | UCHIJAAAAAAAAA  | thebetweenlands          | 3.3.12                       | TheBetweenlands-3.3.12-universal.jar          | 38067d6878811efb38b6a045521cfd80b9b60b38 |
       | UCHIJAAAAAAAAA  | clochecall               | 1.1.1                        | ClocheCall-1.1.1.jar                          | None                                     |
       | UCHIJAAAAAAAAA  | codechickenlib           | 3.2.2.353                    | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAAAAAAAAA  | redstoneflux             | 2.1.0                        | RedstoneFlux-1.12-2.1.0.6-universal.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAAAAAAA  | cofhcore                 | 4.6.0                        | CoFHCore-1.12.2-4.6.0.21-universal.jar        | None                                     |
       | UCHIJAAAAAAAAA  | cofhworld                | 1.3.0                        | CoFHWorld-1.12.2-1.3.0.6-universal.jar        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAAAAAAA  | colytra                  | 1.1.0                        | colytra-1.12.2-1.1.0.jar                      | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | UCHIJAAAAAAAAA  | controlling              | 3.0.6                        | Controlling-3.0.6.jar                         | None                                     |
       | UCHIJAAAAAAAAA  | craftingtweaks           | 8.1.9                        | CraftingTweaks_1.12.2-8.1.9.jar               | None                                     |
       | UCHIJAAAAAAAAA  | ctgui                    | 1.0.0                        | CraftTweaker2-1.12-4.1.9.jar                  | None                                     |
       | UCHIJAAAAAAAAA  | crafttweakerjei          | 2.0.2                        | CraftTweaker2-1.12-4.1.9.jar                  | None                                     |
       | UCHIJAAAAAAAAA  | culinaryconstruct        | 1.1.1                        | culinaryconstruct-1.1.1.jar                   | None                                     |
       | UCHIJAAAAAAAAA  | dirt2path                | 1.7.1                        | dirt2path-1.7.1.jar                           | None                                     |
       | UCHIJAAAAAAAAA  | dungpipe                 | 1.0                          | Dung+Pipe-1.2.jar                             | None                                     |
       | UCHIJAAAAAAAAA  | dsurround                | 3.4.9.15                     | DynamicSurroundings-1.12.2-3.4.9.15.jar       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | UCHIJAAAAAAAAA  | presets                  | 3.4.9.15                     | DynamicSurroundings-1.12.2-3.4.9.15.jar       | None                                     |
       | UCHIJAAAAAAAAA  | dynamictreestc           | 1.12.2-1.1.2                 | DynamicTreesTC-1.12.2-1.1.2.jar               | None                                     |
       | UCHIJAAAAAAAAA  | mysticalmechanics        | 0.4                          | Mystical+Mechanics-0.4.jar                    | None                                     |
       | UCHIJAAAAAAAAA  | embers                   | 1.9hotfix4                   | EmbersRekindled-1.9hotfix4.jar                | None                                     |
       | UCHIJAAAAAAAAA  | eplus                    | 5.0.171                      | EnchantingPlus-1.12.2-5.0.171.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAAAAAAAAA  | enchdesc                 | 1.1.11                       | EnchantmentDescriptions-1.12.2-1.1.11.jar     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAAAAAAAAA  | engineersdoors           | 0.8.0                        | engineers_doors-1.12.2-0.8.0.jar              | None                                     |
       | UCHIJAAAAAAAAA  | erebus                   | 1.0.23                       | Erebus-1.0.23.jar                             | None                                     |
       | UCHIJAAAAAAAAA  | ea                       | 1.0.1                        | ExpandedArcanum-1.0.1.jar                     | None                                     |
       | UCHIJAAAAAAAAA  | extraalchemy             | 0.3.8.5-release              | extraalchemy-0.3.8.5-release.jar              | None                                     |
       | UCHIJAAAAAAAAA  | fairylights              | 2.1.4                        | fairylights-2.1.4-1.12.2.jar                  | None                                     |
       | UCHIJAAAAAAAAA  | familiarfauna            | 1.0.10                       | FamiliarFauna-1.12.2-1.0.10.jar               | None                                     |
       | UCHIJAAAAAAAAA  | foamfix                  | 0.10.2-1.12.2                | foamfix-0.10.2-1.12.2.jar                     | None                                     |
       | UCHIJAAAAAAAAA  | hardcoredarkness         | 2.0                          | HardcoreDarkness-MC1.12.2-2.0.jar             | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | UCHIJAAAAAAAAA  | hopperducts              | 1.5                          | hopperducts-mc1.12-1.5.jar                    | None                                     |
       | UCHIJAAAAAAAAA  | llibrary                 | 1.7.15                       | llibrary-1.7.15-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | UCHIJAAAAAAAAA  | iceandfire               | 1.5.2                        | iceandfire-1.5.2.jar                          | None                                     |
       | UCHIJAAAAAAAAA  | ichunutil                | 7.1.4                        | iChunUtil-1.12.2-7.1.4.jar                    | None                                     |
       | UCHIJAAAAAAAAA  | immersivehempcraft       | 1.12-0.0.6.3                 | Immersive+HempCraft-1.12-0.0.7.0.jar          | None                                     |
       | UCHIJAAAAAAAAA  | immersivepetroleum       | 1.1.9                        | immersivepetroleum-1.12.2-1.1.9.jar           | None                                     |
       | UCHIJAAAAAAAAA  | immersivetech            | 1.3.10                       | immersivetech-1.12-1.3.10.jar                 | None                                     |
       | UCHIJAAAAAAAAA  | mantle                   | 1.12-1.3.2.24                | Mantle-1.12-1.3.2.24.jar                      | None                                     |
       | UCHIJAAAAAAAAA  | inspirations             | 1.12.2-0.2.3                 | Inspirations-1.12.2-0.2.3.jar                 | None                                     |
       | UCHIJAAAAAAAAA  | instantunify             | 1.1.2                        | instantunify-1.12.2-1.1.2.jar                 | None                                     |
       | UCHIJAAAAAAAAA  | inventorytweaks          | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                  | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | UCHIJAAAAAAAAA  | jeibees                  | 0.9.0.5                      | jeibees-0.9.0.5-mc1.12.2.jar                  | None                                     |
       | UCHIJAAAAAAAAA  | jeiintegration           | 1.5.1.36                     | jeiintegration_1.12.2-1.5.1.36.jar            | None                                     |
       | UCHIJAAAAAAAAA  | jeid                     | 1.0.2-24                     | JustEnoughIDs-1.0.2-24.jar                    | None                                     |
       | UCHIJAAAAAAAAA  | justenoughpetroleum      | 0.1                          | JustEnoughPetroleum-0.1.jar                   | None                                     |
       | UCHIJAAAAAAAAA  | kleeslabs                | 5.4.11                       | KleeSlabs_1.12.2-5.4.11.jar                   | None                                     |
       | UCHIJAAAAAAAAA  | lex                      | 1.0.8                        | LibEx-1.12.2-1.0.8.jar                        | None                                     |
       | UCHIJAAAAAAAAA  | librarianlib             | 4.15                         | librarianlib-1.12.2-4.15.jar                  | None                                     |
       | UCHIJAAAAAAAAA  | magipsi                  | 1.3                          | MagicalPsi-1.3.jar                            | None                                     |
       | UCHIJAAAAAAAAA  | minicoal                 | 1.0                          | minicoal-1.12.2-1.0.jar                       | None                                     |
       | UCHIJAAAAAAAAA  | omm                      | 1.0                          | MobDropsStorageBlocks-1.0.jar                 | None                                     |
       | UCHIJAAAAAAAAA  | modnametooltip           | 1.10.0                       | modnametooltip_1.12.2-1.10.0.jar              | None                                     |
       | UCHIJAAAAAAAAA  | morpheus                 | 1.12-3.3.2                   | Morpheus-1.12-3.3.2.jar                       | None                                     |
       | UCHIJAAAAAAAAA  | mousetweaks              | 2.8                          | MouseTweaks-2.8-mc1.12.1.jar                  | None                                     |
       | UCHIJAAAAAAAAA  | mowziesmobs              | 1.4.2                        | mowziesmobs-1.4.2.jar                         | None                                     |
       | UCHIJAAAAAAAAA  | naturalpledge            | 3.0.2                        | NaturalPledge-r3.0.2.jar                      | None                                     |
       | UCHIJAAAAAAAAA  | nbttooltip               | 0.6                          | nbttooltip-0.6.jar                            | None                                     |
       | UCHIJAAAAAAAAA  | nex                      | 2.0.8                        | NetherEx-1.12.2-2.0.8.jar                     | None                                     |
       | UCHIJAAAAAAAAA  | netherportalfix          | 5.3.13                       | NetherPortalFix_1.12.1-5.3.13.jar             | None                                     |
       | UCHIJAAAAAAAAA  | nofov                    | 1.0.1                        | NoFov-MC1.12-1.0.1.jar                        | None                                     |
       | UCHIJAAAAAAAAA  | openmods                 | 0.12                         | OpenModsLib-1.12.2-0.12.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UCHIJAAAAAAAAA  | openblocks               | 1.8                          | OpenBlocks-1.12.2-1.8.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UCHIJAAAAAAAAA  | openglider               | @VERSION@                    | OpenGlider-1.12.1-1.1.0.jar                   | None                                     |
       | UCHIJAAAAAAAAA  | ore_stone_variants       | 3.6                          | ore_stone_variants-3.6.jar                    | None                                     |
       | UCHIJAAAAAAAAA  | parry                    | 1.0                          | parry-1.0-hotfix.jar                          | None                                     |
       | UCHIJAAAAAAAAA  | questionablyimmersive    | @VERSION@                    | questionablyimmersive-1.12.2-0.1.0.jar        | None                                     |
       | UCHIJAAAAAAAAA  | quickleafdecay           | 1.2.4                        | QuickLeafDecay-MC1.12.1-1.2.4.jar             | None                                     |
       | UCHIJAAAAAAAAA  | rpsideas                 | 1.7                          | Random+PSideas+1.7.jar                        | None                                     |
       | UCHIJAAAAAAAAA  | sandro                   | 1.3 BETA-2                   | Redstone+++ver1.3+BETA-2.jar                  | None                                     |
       | UCHIJAAAAAAAAA  | redstoneplusplus         | 1.3 BETA-2                   | Redstone+++ver1.3+BETA-2.jar                  | None                                     |
       | UCHIJAAAAAAAAA  | redstonepaste            | 1.7.5                        | redstonepaste-mc1.12-1.7.5.jar                | None                                     |
       | UCHIJAAAAAAAAA  | redstonepcb              | 0.1                          | RedstonePCB-0.1.jar                           | None                                     |
       | UCHIJAAAAAAAAA  | roots                    | 0.104                        | roots-2-0.104.jar                             | None                                     |
       | UCHIJAAAAAAAAA  | rootsclassic             | 1.12.2-1.1.1                 | RootsClassic-1.12.2-1.1.1.jar                 | None                                     |
       | UCHIJAAAAAAAAA  | rusticthaumaturgy        | 1.0                          | Rustic+Thaumaturgy-2.5.jar                    | None                                     |
       | UCHIJAAAAAAAAA  | rusticbopwoods           | 1.0                          | rusticbopwoods-1.0.jar                        | None                                     |
       | UCHIJAAAAAAAAA  | saltmod                  | 1.12_e_                      | SaltyMod_1.12.1_e.jar                         | None                                     |
       | UCHIJAAAAAAAAA  | snad                     | 1.12.1-1.7.09.16a            | Snad-1.12.1-1.7.09.16a.jar                    | None                                     |
       | UCHIJAAAAAAAAA  | soot                     | 1.5                          | Soot-1.5.jar                                  | None                                     |
       | UCHIJAAAAAAAAA  | spartanweaponry          | beta 1.2.2                   | SpartanWeaponry-1.12.2-beta-1.2.2.jar         | None                                     |
       | UCHIJAAAAAAAAA  | spartanfire              | 0.03                         | spartanfire-0.03.jar                          | None                                     |
       | UCHIJAAAAAAAAA  | spartanshields           | 1.4.1                        | SpartanShields-1.12.2-1.4.1.jar               | None                                     |
       | UCHIJAAAAAAAAA  | stg                      | 1.12.2-1.2.3                 | stg-1.12.2-1.2.3.jar                          | None                                     |
       | UCHIJAAAAAAAAA  | supersoundmuffler        | 1.0.2.9                      | supersoundmuffler-1.12.1-1.0.2.9.jar          | None                                     |
       | UCHIJAAAAAAAAA  | tabula                   | 7.0.0                        | Tabula-1.12.2-7.0.0.jar                       | None                                     |
       | UCHIJAAAAAAAAA  | tcinventoryscan          | 2.0.10                       | ThaumicInventoryScanning_1.12.2-2.0.10.jar    | None                                     |
       | UCHIJAAAAAAAAA  | thaumicjei               | 1.2.1                        | ThaumicJEI-1.12.2-1.5.4-22.jar                | None                                     |
       | UCHIJAAAAAAAAA  | thaumicperiphery         | 0.3.0                        | thaumicperiphery-0.3.0.jar                    | None                                     |
       | UCHIJAAAAAAAAA  | thaumictinkerer          | 1.12.2-5.0-353c71c           | thaumictinkerer-1.12.2-5.0-353c71c.jar        | None                                     |
       | UCHIJAAAAAAAAA  | topaddons                | 1.12.2-1.9.1                 | topaddons-1.12.2-1.9.1.jar                    | None                                     |
       | UCHIJAAAAAAAAA  | vanillafix               | 1.0.9-97                     | VanillaFix-1.0.9-97.jar                       | None                                     |
       | UCHIJAAAAAAAAA  | vanillasatchels          | 1.0.1                        | VanillaSatchels-1.12.2-1.0.1.2-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAAAAAAA  | vanillatools             | 1.1.0                        | VanillaTools-1.12.2-1.1.0.2-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAAAAAAA  | what                     | 0.2                          | WHAT-0.2.jar                                  | None                                     |
       | UCHIJAAAAAAAAA  | wolfarmor                | 2.2.3.6                      | wolfarmor-1.12.2-2.2.3.1798-universal.jar     | None                                     |
       | UCHIJAAAAAAAAA  | candymod                 | 1.1.0                        | candyworld-1.1.0.jar                          | None                                     |
       | UCHIJAAAAAAAAA  | clothesline              | 1.12.2-0.0.1.0               | clothesline-1.12.2-0.0.1.0-bundle.jar         | 3bae2d07b93a5971335cb2de15230c19c103db32 |
       | UCHIJAAAAAAAAA  | kiwi                     | 0.2.2                        | Kiwi-1.12.2-0.2.2.jar                         | None                                     |
       | UCHIJAAAAAAAAA  | cuisine                  | 0.2.3-build381               | Cuisine-0.2.3-build381.jar                    | None                                     |
       | UCHIJAAAAAAAAA  | industrialwires          | 1.7-31                       | IndustrialWires-1.7-31.jar                    | 7e11c175d1e24007afec7498a1616bef0000027d |
       | UCHIJAAAAAAAAA  | librarianliblate         | 4.15                         | librarianlib-1.12.2-4.15.jar                  | None                                     |
  Loaded coremods (and transformers): DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.15.jar)
                                        org.blockartistry.DynSurround.asm.Transformer
                                      ForgelinPlugin (Forgelin-1.7.4.jar)
                                        
                                      OpenEyePlugin (OpenEye-1.12.2-0.8.jar)
                                        openeye.asm.MultiTransformer
                                      AstralCore (astralsorcery-1.12.2-1.9.4.jar)
                                        
                                      JEIDLoadingPlugin (JustEnoughIDs-1.0.2-24.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
                                        com.teamwizardry.librarianlib.asm.LibLibTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
                                        
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.jar)
                                        openmods.core.OpenModsClassTransformer
                                      NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
                                        net.fybertech.nwr.NWRTransformer
                                      clothesline-hooks (clothesline-hooks-1.12.2-0.0.1.0.jar)
                                        com.jamieswhiteshirt.clothesline.hooks.plugin.ClassTransformer
                                      LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
                                      CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
                                        
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      LoadingPlugin (Quark-r1.5-130.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
                                        lumien.hardcoredarkness.asm.ClassTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      Botania Tweaks Core (botaniatweaks-1.7.jar)
                                        quaternary.botaniatweaks.asm.BotaniaTweakerTransformer
                                      ColytraLoadingPlugin (colytra-1.12.2-1.1.0.jar)
                                        c4.colytra.asm.ElytraTransformer
                                      llibrary (llibrary-core-1.0.8-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
                                        mods.betterfoliage.loader.BetterFoliageTransformer
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.12-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13521 Compatibility Profile Context 24.20.11016.4' Renderer: 'Radeon RX 580 Series'
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  Pulsar/inspirations loaded Pulses: - InspirationsShared (Enabled/Forced)
                                     - InspirationsBuilding (Enabled/Not Forced)
                                     - InspirationsUtility (Enabled/Not Forced)
                                     - InspirationsTools (Enabled/Not Forced)
                                     - InspirationsRecipes (Enabled/Not Forced)
                                     - InspirationsTweaks (Enabled/Not Forced)
                                     - InspirationsShared (Enabled/Forced)
                                     - TheOneProbePlugin (Enabled/Not Forced)
  Suspected Mods: Forestry (forestry)

**Comment by JamiesWhiteShirt** [comment]
I guess this happens on when you try to log on to a server. This seems more related to Forestry than Clothesline.

Maybe adding Clothesline provoked a Forestry error, maybe not. I would suggest temporarily removing Clothesline and seeing if the issue still appears.

I do not think there is much I can do about it at the moment.
